### ISSUE TITLE
Oh!  There is a bug!

### ISSUE THREAD

**Issue by gjlccc** [Chinese-Gemini-Star/StellarWander#1]
When I make a reservation as a tourist, I cancel the reservation. When I tried to make an appointment again, it would tell me that I had made an appointment。

**Comment by Chinese-Gemini-Star** [comment]
能给出具体的问题复现方式吗？我这里测试出来没有什么问题。

**Comment by Chinese-Gemini-Star** [comment]
Can you give a specific way to reproduce the problem?  I tested it out here and there is no problem.

**Comment by gjlccc** [comment]
> 能给出具体的问题复现方式吗？我这里测试出来没有什么问题。

我私发给你了哦

**Comment by gjlccc** [comment]
> 
I sent it to you privately

**Comment by Chinese-Gemini-Star** [comment]
All right. I think I have found and I will  solve this promble.
